# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1pvr3BYNkGgNGMbCDnPxja-FQXL2fo14P
"""

import string

txt  = "Лично я лучше всего обучаюсь при помощи небольшого работающего кода, с которым могу поиграться. В этом пособии мы научимся алгоритму обратного распространения ошибок на примере небольшой нейронной сети, реализованной на Python с которым могу поиграться. В этом пособии мы научимся алгоритму"
txt_lower = txt.lower()

words_ower_list = []
words_ower_list = txt_lower.split()
print(words_ower_list)

from collections import Counter

top_words_list = []
top_words_list = Counter(words_ower_list)
print(top_words_list)

# выводится список каунтеров для каждого ключа. 
# требуется: найти самые высокие значения и гет их ключи

counters_value = top_words_list.values()
# counters_value = top_words_list.values()
print(counters_value)